### ISSUE TITLE
Add debug mode to show output

### ISSUE THREAD

**Issue by fluxsauce** [flipstewart/gifhorse-cli#5]
Called `--mouth -m Inspect raw output` please

![image](https://cloud.githubusercontent.com/assets/976391/9041106/125504f4-39bb-11e5-8796-3e79e2f25539.png)

**Comment by flipstewart** [comment]
I'll accept a PR for this one, but it's not high on my list right now tbh.

**Comment by flipstewart** [comment]
ffmpeg: `-v debug`

**Comment by flipstewart** [comment]
This just became a lot simpler; will revisit.

**Comment by fluxsauce** [comment]
Fantastic!

> `verbosity`

Dang, oh well

**Comment by flipstewart** [comment]
@fluxsauce Yeah... I could put in an additional boolean for verbose output, but... yeah.
